title: GSOPs Documentation
description: Gaussian Splat Operators for TouchDesigner
baseurl: /TouchDesigner-GSOPs-Docs
remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-remote-theme

color_scheme: dark

aux_links:
  "Lake Heckaman":
    - "https://www.lakeheckaman.com"

nav_enabled: true
