title: GSOPs Documentation
description: Gaussian Splat Operators for TouchDesigner
theme: just-the-docs

color_scheme: dark

aux_links:
  "Lake Heckaman":
    - "https://www.lakeheckaman.com"

nav_enabled: true
